server:
  port: 8080
logging:
  level:
    org.jline: OFF
    io.github.francoisc: DEBUG
spring:
  application:
    name: farkle
  main:
    banner-mode: off

  shell:
    interactive:
      enabled: true
    script:
      enabled: true
